apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kgxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kgxy
    app.kubernetes.io/part-of: ci10t-786-0037-app
  name: devfile-sample-kgxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kgxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kgxy
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0037-tenant/ci10t-786-0037-app/devfile-sample-kgxy@sha256:9c93a5020d052cb09985973837813c9c338a84ed7c435bbe1f43a7f356c026dd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
