apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kgxy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0037-tenant/ci10t-786-0037-app/devfile-sample-kgxy@sha256:9c93a5020d052cb09985973837813c9c338a84ed7c435bbe1f43a7f356c026dd
        name: my-nodejs
        resources: {}
status: {}
